import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://www.google.com/")
time.sleep(3)
driver.maximize_window()
search_field = driver.find_element(By.ID, 'APjFqb')
search_field.send_keys('AAUP')
search_field.submit()
time.sleep(3)
search_field = driver.find_element(By.PARTIAL_LINK_TEXT, 'جامعة')
search_field.click()
time.sleep(3)
search_field = driver.find_element(By.PARTIAL_LINK_TEXT, 'التخصصات')
driver.execute_script("arguments[0].scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });", search_field)
time.sleep(3)
search_field.click()
time.sleep(3)
search_field = driver.find_element(By.ID, 'campus')
driver.execute_script("arguments[0].scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });", search_field)
time.sleep(3)
search_field.send_keys('الحرم الرئيسي - جنين')
time.sleep(3)
search_field = driver.find_element(By.ID, 'degree')
search_field.send_keys('البكالوريوس')
time.sleep(3)
search_field = driver.find_element(By.ID, 'major')
search_field.send_keys('هندسة أنظمة الحاسوب')
time.sleep(3)
search_field = driver.find_element(By.ID, 'branch-category')
driver.execute_script("arguments[0].scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });", search_field)
time.sleep(3)
search_field.send_keys('ثانوية عامة فلسطينية')
time.sleep(3)
search_field = driver.find_element(By.ID, 'school')
search_field.send_keys('العلمي')
time.sleep(3)
search_field = driver.find_element(By.ID, 'avg')
search_field.send_keys('90.7')
time.sleep(3)
search_field = driver.find_element(By.ID, 'showVal')
search_field.click()
time.sleep(3)
search_field = driver.find_element(By.XPATH, '//*[@id="txtHint"]/div[1]/div[1]/div/strong/span')
driver.execute_script("arguments[0].scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });", search_field)
time.sleep(6)
driver.close()